basePath: /api/v1
definitions:
  controller.loginRequest:
    properties:
      email:
        example: test@example.com
        type: string
      password:
        example: test
        type: string
    required:
    - email
    - password
    type: object
  controller.loginResponse:
    properties:
      code:
        example: 200
        type: integer
      expier:
        example: "2024-09-20T03:12:53+09:00"
        type: string
      token:
        type: string
    type: object
  model.TaskEntity:
    properties:
      deadline:
        type: string
      memo:
        type: string
      title:
        type: string
    type: object
  responses.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  responses.SuccessResponse:
    properties:
      data: {}
    type: object
info:
  contact: {}
  description: このswaggerはyarujunのAPIを定義しています。 JWTトークンの前に"Bearer"を追加してください。
  license:
    name: suzuhiki
  title: gin-swagger todos
  version: "1.0"
paths:
  /auth/refresh_token:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      security:
      - BearerAuth: []
      summary: 認証情報の更新
  /auth/tasks:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responses.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.TaskEntity'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      security:
      - BearerAuth: []
      summary: Todo一覧を配列で返す
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body param
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/controller.loginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: ログイン
  /test:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: Hello, World!!!!!!!!
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: hello worldを返す
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
