definitions:
  model.TaskEntity:
    properties:
      deadline:
        type: string
      memo:
        type: string
      title:
        type: string
    type: object
  responses.ErrorResponse:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  responses.SuccessResponse:
    properties:
      data: {}
    type: object
info:
  contact: {}
  description: このswaggerはyarujunのAPIを定義しています。
  license:
    name: suzuhiki
  title: gin-swagger todos
  version: "1.0"
paths:
  /:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responses.SuccessResponse'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.TaskEntity'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Todo一覧を配列で返す
  /test:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/responses.SuccessResponse'
            - properties:
                data:
                  items:
                    type: string
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: hello worldを返す
swagger: "2.0"
